name: CodSpeed

on:
  push:
    branches:
      - "main" # or "master"
  pull_request:
  # `workflow_dispatch` allows CodSpeed to trigger backtest
  # performance analysis in order to generate initial data.
  workflow_dispatch:

jobs:
  benchmarks:
    name: Run benchmarks
    runs-on: ubuntu-latest
    env:
      CODSPEED_LOG: debug
    steps:
      - uses: actions/checkout@v4
        with: 
          token: ${{ secrets.PAT }}
          lfs: true
      - run: git config --global url."https://not-matthias:${{ secrets.PAT }}@github.com".insteadOf "https://github.com"

      # - name: Cache opencv
      #   uses: actions/cache@v3
      #   with:
      #     path: /usr/local
      #     key: ${{ runner.os }}-build-tests-${{ hashFiles('**/CMakeLists.txt', '/usr/local/**') }}

      - uses: extractions/setup-just@v2

      - run: sudo apt-get update && sudo apt-get install -y build-essential checkinstall git cmake g++ wget unzip pkg-config yasm git
      - uses: Dovyski/setup-opencv-action@v1.1
        with:
          opencv-version: '4.0.0'
          CMAKE_BUILD_TYPE: RelWithDebInfo
          install-deps: false

      # - run: sudo apt-get update && sudo apt install -y libopencv-dev
          
      - name: Build the benchmark target(s)
        run: |
          just build-instrumentation
          just run

      - name: Run the benchmarks
        uses: CodSpeedHQ/action@v3
        with:
          run: build/cv-bench
          token: ${{ secrets.CODSPEED_TOKEN }}
          upload-url: https://api.staging.preview.codspeed.io/upload

  benchmarks-walltime:
    name: Run walltime benchmarks
    runs-on: codspeed-macro-staging
    env:
      CODSPEED_LOG: debug
    steps:
      - uses: actions/checkout@v4
        with: 
          token: ${{ secrets.PAT }}
          lfs: true
      - run: git config --global url."https://not-matthias:${{ secrets.PAT }}@github.com".insteadOf "https://github.com"

      - uses: extractions/setup-just@v2
      # - uses: Dovyski/setup-opencv-action@v1.1
      #   with:
      #     opencv-version: '4.0.0'
      #     install-deps: false
      
      - run: sudo apt-get update && sudo apt install -y libopencv-dev
      
      - name: Build the benchmark target(s)
        run: |
          just build-walltime
          just run


      - name: Run the benchmarks
        uses: CodSpeedHQ/action@v3
        with:
          run: build/cv-bench
          token: ${{ secrets.CODSPEED_TOKEN }}
          upload-url: https://api.staging.preview.codspeed.io/upload
          
